### ISSUE TITLE
Email Deployer

### ISSUE THREAD

**Issue by hhsnopek** [carrot/ship#15]
use [nodemailer](//www.nodemailer.com/) for configuring & sending email

purpose:
- zip, tarball, etc. the project
- email's user/client

ship.conf

```
    service: gmail
    user: foo@gmail.com #we could also append the service for the email?
    pass: bar
    recipient:
    subject:
    message:
```

subject & message could either be dynamic or static.

request from @samccone via https://github.com/jenius/roots/issues/373
